---
name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
    paths-ignore:
      - '**.md'
env:
  TERM: dumb
  TMPDIR: "/tmp"
jobs:
  checks:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: bazel-contrib/setup-bazel@0.9.1
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}_${{ hashFiles('.bazelversion') }}
          repository-cache: true
      - name: build
        run: bazel build //...
      - name: formatting
        run: |
          # I need to figure this out, but the lock file changes when running on linux (I created it on mac)
          # See https://github.com/bazelbuild/rules_rust/pull/2453
          bazel run //tools:format
          git checkout MODULE.bazel.lock
          if [[ $(git status --porcelain) ]]; then echo "**** run 'bazel run //tools:format' to fix formatting errors"; git diff; exit 1; fi
          bazel run @rules_rust//:rustfmt
          git checkout MODULE.bazel.lock
          if [[ $(git status --porcelain) ]]; then echo "**** run 'bazel run @rules_rust//:rustfmt' to fix formatting errors"; git diff; exit 1; fi
      - name: test
        run: bazel test //...
