---
name: Create Release
on:
  push:
    tags:
      - 'v*'
jobs:
  build_release_binaries:
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm, macos-13, macos-15]
        include:
          - os: ubuntu-24.04
            artifact_postfix: linux_x86
          - os: macos-13
            artifact_postfix: macos_x86
          - os: ubuntu-24.04-arm
            artifact_postfix: linux_arm64
          - os: macos-15
            artifact_postfix: macos_arm64
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: bazel-contrib/setup-bazel@0.9.1
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true
      - name: build
        run: bazel build //:oxc_dts_emit -c opt
      - name: store binary
        uses: actions/upload-artifact@v4.6.0
        with:
          path: bazel-bin/oxc_dts_emit
          name: oxc_dts_emit_${{ matrix.artifact_postfix }}
  release_creation:
    needs: build_release_binaries
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4.1.8
        with:
          path: ./artifacts
      - name: Generate sha for artifacts
        run: |
          echo "oxc_dts_emit v${{ github.ref_name }} from tag ${{ github.ref }} ${{ github.sha }}." > artifacts/body.txt
          echo "" >> artifacts/body.txt
          echo "Binaries and SHA256:" >> artifacts/body.txt
          sha256sum artifacts/oxc_dts_emit_linux_arm64/oxc_dts_emit >> artifacts/body.txt
          sha256sum artifacts/oxc_dts_emit_linux_x86/oxc_dts_emit >> artifacts/body.txt
          sha256sum artifacts/oxc_dts_emit_macos_arm64/oxc_dts_emit >> artifacts/body.txt
          sha256sum artifacts/oxc_dts_emit_macos_x86/oxc_dts_emit >> artifacts/body.txt
      - name: Release
        uses: softprops/action-gh-release@v2.2.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          make_latest: true
          generate_release_notes: true
          body_path: artifacts/body.txt
          files: |
            artifacts/oxc_dts_emit_linux_arm64/oxc_dts_emit
            artifacts/oxc_dts_emit_linux_x86/oxc_dts_emit
            artifacts/oxc_dts_emit_macos_arm64/oxc_dts_emit
            artifacts/oxc_dts_emit_macos_x86/oxc_dts_emit
