---
name: Create Release
on:
  push:
    tags:
      - 'v*'
jobs:
  build_release_binaries:
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm, macos-13, macos-15]
        include:
          - os: ubuntu-24.04
            artifact_postfix: linux_x86
          - os: macos-13
            artifact_postfix: macos_x86
          - os: ubuntu-24.04-arm
            artifact_postfix: linux_arm64
          - os: macos-15
            artifact_postfix: macos_arm64
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: bazel-contrib/setup-bazel@0.9.1
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}_${{ matrix.artifact_postfix }}_${{ hashFiles('.bazelversion') }}
          repository-cache: true
      - name: build release
        run: bazel build --config opt //:oxc_dts_emit
      - name: make executable
        run: chmod +x bazel-bin/oxc_dts_emit
      - name: Compress binaries
        uses: svenstaro/upx-action@2.4.1
        with:
          args: --best
          files: |
            bazel-bin/oxc_dts_emit
      - name: store binary
        uses: actions/upload-artifact@v4.6.0
        with:
          path: bazel-bin/oxc_dts_emit
          name: oxc_dts_emit_${{ matrix.artifact_postfix }}
          if-no-files-found: error
  release_creation:
    needs: build_release_binaries
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4.1.8
        with:
          path: ./artifacts
      - name: pack artifacts to os/arch archives
        run: |
          chmod +x artifacts/oxc_dts_emit_linux_arm64/oxc_dts_emit
          tar -czvf artifacts/oxc_dts_emit_linux_arm64.tar.gz -C artifacts/oxc_dts_emit_linux_arm64 oxc_dts_emit
          chmod +x artifacts/oxc_dts_emit_linux_x86/oxc_dts_emit
          tar -czvf artifacts/oxc_dts_emit_linux_x86.tar.gz -C artifacts/oxc_dts_emit_linux_x86 oxc_dts_emit
          chmod +x artifacts/oxc_dts_emit_macos_arm64/oxc_dts_emit
          tar -czvf artifacts/oxc_dts_emit_macos_arm64.tar.gz -C artifacts/oxc_dts_emit_macos_arm64 oxc_dts_emit
          chmod +x artifacts/oxc_dts_emit_macos_x86/oxc_dts_emit
          tar -czvf artifacts/oxc_dts_emit_macos_x86.tar.gz -C artifacts/oxc_dts_emit_macos_x86 oxc_dts_emit
      - name: Generate sha for artifacts
        run: |
          echo "The \`oxc_dts_emit\` binaries for tag \`${{ github.ref_name }}\` were built from ${{ github.sha }}." > artifacts/body.txt
          echo "" >> artifacts/body.txt
          echo "### <ins>Binaries and SHA256:</ins>" >> artifacts/body.txt
          echo "\`\`\`" >> artifacts/body.txt
          sha256sum artifacts/oxc_dts_emit_linux_arm64.tar.gz >> artifacts/body.txt
          sha256sum artifacts/oxc_dts_emit_linux_x86.tar.gz >> artifacts/body.txt
          sha256sum artifacts/oxc_dts_emit_macos_arm64.tar.gz >> artifacts/body.txt
          sha256sum artifacts/oxc_dts_emit_macos_x86.tar.gz >> artifacts/body.txt
          echo "\`\`\`" >> artifacts/body.txt
      - name: Release
        uses: softprops/action-gh-release@v2.2.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          make_latest: true
          generate_release_notes: true
          body_path: artifacts/body.txt
          append_body: true
          files: |
            artifacts/oxc_dts_emit_linux_arm64.tar.gz
            artifacts/oxc_dts_emit_linux_x86.tar.gz
            artifacts/oxc_dts_emit_macos_arm64.tar.gz
            artifacts/oxc_dts_emit_macos_x86.tar.gz
